### PR TITLE
Add expire time for bundles

### PR DESCRIPTION
**Pull request by TanGuy4**
Hi,

I find your project on RapidAPI.com.

I use it and want to be able to get in how much time the bundles expire.
So I fork it and add this feature (I get the countdown time).

### CODE REVIEW

**Comment by andrerfcsantos** [comment]
Thanks for your interest in the project.

Rather than returning the time remaining, it would be better for the API to return the time at which a bundle ends, and let the clients compute the time remaining.

Note that this API scrapes the humble bundle site regularly and always returns the result of the last scrapping. It does not scrape the humble bundle site at every request. This means that any value we give for the time remaining will be outdated, because it refers to the time remaining when the scraping was done, not when the client requested.

So, I think the solution for this would be to return the time at which the bundle will end. This can be done by adding the current time to the time remaining. However, this result must be cached somehow, to ensure the API always returns the same result for a particular bundle. Additionally, it's probably a good idea to add some checks to ensure we return a reasonable result. For instance, if when adding the current time to the time remaining to get the end time/day of the bundle we get something like "2021-08-30T19:00:07", we probably should fix it to  "2021-08-30T19:00:00" (note the difference in the seconds).

Would you like to try to implement something like this?

**Comment by TanGuy4** [comment]
I agree with you, I will try to implement something like that.

**Comment by andrerfcsantos** [comment]
> I agree with you, I will try to implement something like that.

Great!

One thing tat might help you: notice that each bundle page has some JSON inside script tags that has some information about the bundle, including the time at a bundle will end. This is an example:

```json
  <script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": ["Product"],
    "name": "Humble Jackbox Summer Party Bundle ",
    "image": "https://hb.imgix.net/88e8d67ae540b6c5f4a351a27c2562a117db788c.png?auto=compress,format&amp;h=170&amp;w=1200&amp;s=7e3a4029d1487f569d8f13f127e16919",
    "offers": {
      "@type": "AggregateOffer",
      "highPrice": "1.00",
      "lowPrice": "16.87",
      "priceCurrency": "EUR",
      "offerCount": "4",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2021-09-03T18:00:00",
      "availableDeliveryMethod": "http://purl.org/goodrelations/v1#DeliveryModeDirectDownload"

    },
    "url": "/" + basic_data.page_url
  }
  </script>
```

Messing with the console a bit, I managed to extract the json inside it:

```js
let scripts = document.querySelectorAll("script[type='application/ld+json']")

// needed to remove the "url" bit which makes the script invalid JSON
let cleanJSON = scripts[0].innerText.replace(/,\s+\"url\": \"\/\" \+ basic_data\.page_url/gm, "")

let info = JSON.parse(cleanJSON)

console.log(info.offers.availabilityEnds) // "2021-09-03T18:00:00"
```

Shouldn't be hard to replicate this into Playwright

**Comment by TanGuy4** [comment]
> One thing tat might help you: notice that each bundle page has some JSON inside script tags that has some information > about the bundle, including the time at a bundle will end. This is an example:
  ```<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": ["Product"],
    "name": "Humble Jackbox Summer Party Bundle ",
    "image": "https://hb.imgix.net/88e8d67ae540b6c5f4a351a27c2562a117db788c.png?auto=compress,format&amp;h=170&amp;w=1200&amp;s=7e3a4029d1487f569d8f13f127e16919",
    "offers": {
      "@type": "AggregateOffer",
      "highPrice": "1.00",
      "lowPrice": "16.87",
      "priceCurrency": "EUR",
      "offerCount": "4",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2021-09-03T18:00:00",
      "availableDeliveryMethod": "http://purl.org/goodrelations/v1#DeliveryModeDirectDownload"

    },
    "url": "/" + basic_data.page_url
  }
  </script>
```
Yeah I have see that too in the console.
I am a newbie to Playwright so it will take some time. But I found some way to do it in the documentation. I keep trying.

**Comment by TanGuy4** [comment]
It's done. And it works!

**Comment by andrerfcsantos** [comment]
Awesome!

I just made a little change to make the timestamps include timezone information (UTC) and cleaned the old code.

Thank you for your contribution!

**Comment by andrerfcsantos** [comment]
Changes are live at https://humble.asantosdev.com/bundles or via RapidAPI.

**Pull request merged**
